### ISSUE TITLE
Crash when generating chunks

### ISSUE THREAD

**Issue by deadspidervenom** [Cryptic-Mushroom/The-Midnight#244]
So the reason i know this is chunk loading, is if i load the world after the crash and stay still no issue, moment i move and a new chunk loads it crashes.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreModLoader (Sound-Physics-Mod-1.12.2.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  HatedMobsLoadingPlugin (hatedmobs-1.4.1.jar)
  CosmicLibFakeCoreMod (CosmicLib-1.12.2-0.4.0.BETA.jar)
  BlurPlugin (Blur-1.0.4-14.jar)
  TickrateChanger (TickrateChanger-1.0.14.jar)
  midnight (themidnight-0.3.5.jar)
  SCFMLCorePlugin (StalkerCreepers-1.12.1.jar)
  PassableLeavesCore (PassableLeavesCore-1.12.2-1.0.0.jar)
  LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 7/1/19 10:21 PM
Description: Exception ticking world

java.lang.RuntimeException: Already decorating
	at com.mushroom.midnight.common.biome.MidnightBiomeDecorator.func_180292_a(MidnightBiomeDecorator.java:33)
	at com.mushroom.midnight.common.biome.cavern.CavernousBiome.decorate(CavernousBiome.java:37)
	at com.mushroom.midnight.common.world.MidnightChunkGenerator.func_185931_b(MidnightChunkGenerator.java:200)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:980)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.World.func_175726_f(World.java:305)
	at net.minecraft.world.World.func_180495_p(World.java:911)
	at alexiy.secure.contain.protect.Utils.canReplaceBlock(Utils.java:543)
	at alexiy.secure.contain.protect.events.ServerEvents.generateContainmentChambers(ServerEvents.java:190)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_408_ServerEvents_generateContainmentChambers_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at com.mushroom.midnight.common.biome.MidnightBiomeDecorator.func_150513_a(MidnightBiomeDecorator.java:58)
	at com.mushroom.midnight.common.biome.MidnightBiomeDecorator.func_180292_a(MidnightBiomeDecorator.java:39)
	at com.mushroom.midnight.common.biome.cavern.CavernousBiome.decorate(CavernousBiome.java:37)
	at com.mushroom.midnight.common.world.MidnightChunkGenerator.func_185931_b(MidnightChunkGenerator.java:200)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:985)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:226)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.mushroom.midnight.common.biome.MidnightBiomeDecorator.func_180292_a(MidnightBiomeDecorator.java:33)
	at com.mushroom.midnight.common.biome.cavern.CavernousBiome.decorate(CavernousBiome.java:37)
	at com.mushroom.midnight.common.world.MidnightChunkGenerator.func_185931_b(MidnightChunkGenerator.java:200)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:980)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.World.func_175726_f(World.java:305)
	at net.minecraft.world.World.func_180495_p(World.java:911)
	at alexiy.secure.contain.protect.Utils.canReplaceBlock(Utils.java:543)
	at alexiy.secure.contain.protect.events.ServerEvents.generateContainmentChambers(ServerEvents.java:190)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_408_ServerEvents_generateContainmentChambers_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at com.mushroom.midnight.common.biome.MidnightBiomeDecorator.func_150513_a(MidnightBiomeDecorator.java:58)
	at com.mushroom.midnight.common.biome.MidnightBiomeDecorator.func_180292_a(MidnightBiomeDecorator.java:39)
	at com.mushroom.midnight.common.biome.cavern.CavernousBiome.decorate(CavernousBiome.java:37)
	at com.mushroom.midnight.common.world.MidnightChunkGenerator.func_185931_b(MidnightChunkGenerator.java:200)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:985)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:226)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['lilcanvr'/652, l='New World', x=154.38, y=82.00, z=162.81]]
	Chunk stats: ServerChunkCache: 213 Drop: 0
	Level seed: 7340580690677761898
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 326310824 bytes (311 MB) / 2023227392 bytes (1929 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 32
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 49 mods loaded, 49 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                 | Version        | Source                                 | Signature                                |
	|:------ |:------------------ |:-------------- |:-------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft          | 1.12.2         | minecraft.jar                          | None                                     |
	| LCHIJA | mcp                | 9.42           | minecraft.jar                          | None                                     |
	| LCHIJA | FML                | 8.0.99.99      | forge-1.12.2-14.23.5.2838.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge              | 14.23.5.2838   | forge-1.12.2-14.23.5.2838.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | passableleavescore | 1.0.0          | minecraft.jar                          | None                                     |
	| LCHIJA | abyssvoice         | 0.1.3          | AbyssVoice+[0.1.3].jar                 | None                                     |
	| LCHIJA | ageingmobs         | 1.1            | Ageing-Mobs-1.1.jar                    | None                                     |
	| LCHIJA | baubles            | 1.5.2          | Baubles-1.12-1.5.2.jar                 | None                                     |
	| LCHIJA | bedrockbgone       | 5.0.8          | BedrockBGone-1.12.2-5.0-b8.jar         | None                                     |
	| LCHIJA | blur               | 1.0.4-14       | Blur-1.0.4-14.jar                      | None                                     |
	| LCHIJA | bookshelf          | 2.3.585        | Bookshelf-1.12.2-2.3.585.jar           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | spawnermod         | 1.0-1.12.2     | branders-enh-mb-spwnrs-v1.0-1.12.2.jar | None                                     |
	| LCHIJA | extendedrenderer   | v1.0           | coroutil-1.12.1-1.2.32.jar             | None                                     |
	| LCHIJA | coroutil           | 1.12.1-1.2.32  | coroutil-1.12.1-1.2.32.jar             | None                                     |
	| LCHIJA | configmod          | v1.0           | coroutil-1.12.1-1.2.32.jar             | None                                     |
	| LCHIJA | cosmiclib          | 0.4.0          | CosmicLib-1.12.2-0.4.0.BETA.jar        | d3974446c00f9f1d275edce305771eeddf30c658 |
	| LCHIJA | dmonsters          | 1.7            | Deadly+Monsters+1.71.jar               | None                                     |
	| LCHIJA | eyesinthedarkness  | 0.0.5          | EyesInTheDarkness-0.0.5.jar            | None                                     |
	| LCHIJA | grue               | 1.4.0          | Grue-1.12.2-1.4.0.jar                  | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | hardcoredarkness   | 2.0            | HardcoreDarkness-MC1.12.2-2.0.jar      | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | llibrary           | 1.7.19         | llibrary-1.7.19-1.12.2.jar             | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | hatedmobs          | 1.4.1          | hatedmobs-1.4.1.jar                    | None                                     |
	| LCHIJA | hidenames          | 1.4            | HideNames-1.12-1.4.jar                 | None                                     |
	| LCHIJA | howlitdo           | 1.1            | HowlItDo-1.1.jar                       | None                                     |
	| LCHIJA | jei                | 4.15.0.268     | jei_1.12.2-4.15.0.268.jar              | None                                     |
	| LCHIJA | meanmobs           | 1.0.2          | meanmobs-[1.0.2]-{1.12.2}.jar          | None                                     |
	| LCHIJA | muchmorespiders    | 1.2            | mmsr-1.0.2-1.12.2.jar                  | None                                     |
	| LCHIJA | mobends            | 0.24           | mobends-0.24_for_MC-1.12.jar           | None                                     |
	| LCHIJA | torotraits         | 1.12-1         | torotraits-1.12-1.jar                  | None                                     |
	| LCHIJA | nemesissystem      | 1.12.1-2       | nemesissystem-1.12.1-2.jar             | None                                     |
	| LCHIJA | nightmares         | 1.0.4          | Nightmares-1.12.2-1.0.4.jar            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | realistictorches   | 2.1.1          | RealisticTorches-1.12.2-2.1.1.jar      | None                                     |
	| LCHIJA | tiffitlib          | 1.0.3          | tiffitlib-1.0.3.jar                    | None                                     |
	| LCHIJA | sanity             | 1.0.3          | sanity-1.0.3.jar                       | None                                     |
	| LCHIJA | scp                | 2.1.1          | SCP+Lockdown-1.12.2-2.1.1-beta.jar     | None                                     |
	| LCHIJA | tickratechanger    | 1.0.14         | TickrateChanger-1.0.14.jar             | None                                     |
	| LCHIJA | sleepingoverhaul   | 1.0.0          | SleepingOverhaul-1.12.2-1.0.0.jar      | d3974446c00f9f1d275edce305771eeddf30c658 |
	| LCHIJA | smelly             | 1.0.3          | smelly-1.12-1.0.4-9.jar                | None                                     |
	| LCHIJA | soundphysics       | 1.0.4          | Sound-Physics-Mod-1.12.2.jar           | None                                     |
	| LCHIJA | beneath            | 1.5.1          | The+Beneath-1.12.2-1.5.1.jar           | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | thutcore           | 5.21.0         | thutcore-1.12.2-5.21.0.jar             | None                                     |
	| LCHIJA | thutcore_compat    | 1.0            | thutcore-1.12.2-5.21.0.jar             | None                                     |
	| LCHIJA | thuttech           | 6.1.6          | thuttech-1.12.2-6.1.6.jar              | None                                     |
	| LCHIJA | tumbleweed         | 1.11-0.4.5     | tumbleweed-1.11-0.4.5.jar              | None                                     |
	| LCHIJA | worleycaves        | 1.4.1          | worleycaves-1.4.1.jar                  | None                                     |
	| LCHIJA | zombieawareness    | 1.12.1-1.11.16 | zombieawareness-1.12.1-1.11.16.jar     | None                                     |
	| LCHIJA | passableleaves     | 2.0.0          | PassableLeaves-1.12.2-2.0.0.jar        | None                                     |
	| LCHIJA | midnight           | 0.3.5          | themidnight-0.3.5.jar                  | None                                     |
	| LCHIJA | weeping-angels     | 1.12.2-37      | weeping-angels-37.jar                  | None                                     |

	Loaded coremods (and transformers): 
CoreModLoader (Sound-Physics-Mod-1.12.2.jar)
  com.sonicether.soundphysics.CoreModInjector
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
HatedMobsLoadingPlugin (hatedmobs-1.4.1.jar)
  fr.uranoscopidae.hatedmobs.asm.HatedMobsTransformer
CosmicLibFakeCoreMod (CosmicLib-1.12.2-0.4.0.BETA.jar)
  
BlurPlugin (Blur-1.0.4-14.jar)
  com.tterrag.blur.BlurTransformer
TickrateChanger (TickrateChanger-1.0.14.jar)
  me.guichaguri.tickratechanger.TickrateTransformer
midnight (themidnight-0.3.5.jar)
  com.mushroom.midnight.core.transformer.MidnightClassTransformer
SCFMLCorePlugin (StalkerCreepers-1.12.1.jar)
  atomicstryker.stalkercreepers.common.SCTransformer
PassableLeavesCore (PassableLeavesCore-1.12.2-1.0.0.jar)
  teamrtg.passableleaves.asm.PassableLeavesTransformer
LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['lilcanvr'/652, l='New World', x=154.38, y=82.00, z=162.81]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 399.24
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12 `
```

**Comment by five0five** [comment]
if this occurs on 1.14, reopen
