### ISSUE TITLE
Dark Willow Sapling Crash [1.12.2]

### ISSUE THREAD

**Issue by GalacticRuler** [Cryptic-Mushroom/The-Midnight#290]
Attempting to grow a dark-willow in the overworld leads to the following null-pointer exception crash:

```
java.lang.NullPointerException: Unexpected error
	at com.mushroom.midnight.common.world.template.TemplateCompiler.compile(TemplateCompiler.java:74)
	at com.mushroom.midnight.common.world.feature.TemplateTreeFeature.placeFeature(TemplateTreeFeature.java:55)
	at com.mushroom.midnight.common.world.feature.MidnightAbstractFeature.func_180709_b(MidnightAbstractFeature.java:17)
	at com.mushroom.midnight.common.block.BlockMidnightSapling.func_176474_b(BlockMidnightSapling.java:77)
	at logictechcorp.netherex.handler.InputHandler.onBoneMealUse(InputHandler.java:177)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_306_InputHandler_onBoneMealUse_BonemealEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onApplyBonemeal(ForgeEventFactory.java:455)
	at net.minecraft.item.ItemDye.applyBonemeal(ItemDye.java:111)
	at net.minecraft.item.ItemDye.func_180614_a(ItemDye.java:55)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:187)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:467)
	at net.optifine.override.PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

```

**Comment by GalacticRuler** [comment]
This actually seems to occur with all Midnight plants/mushrooms when bonemeal is applied anywhere in the overworld

**Comment by nathandstory** [comment]
I am getting the same error, with a completely different setup, however we both have NetherEX in common it seems. I was using bonemeal on a silverwood sapling in the overworld. I'm going to see if I can fix it and I'll get back here if no one else figures it out. 

`java.lang.NullPointerException: Unexpected error
	at com.pg85.otg.forge.ForgeWorld.getObjectSpawner(ForgeWorld.java:1349)
	at com.pg85.otg.forge.ForgeWorld.getChunk(ForgeWorld.java:586)
	at com.pg85.otg.forge.ForgeWorld.getMaterial(ForgeWorld.java:782)
	at com.pg85.otg.forge.events.SaplingListener$SaplingGrower.<init>(SaplingListener.java:38)
	at com.pg85.otg.forge.events.SaplingListener$SaplingGrower.<init>(SaplingListener.java:27)
	at com.pg85.otg.forge.events.SaplingListener.onSaplingGrow(SaplingListener.java:169)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2242_SaplingListener_onSaplingGrow_SaplingGrowTreeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.terraingen.TerrainGen.saplingGrowTree(TerrainGen.java:108)
	at thaumcraft.common.blocks.world.plants.BlockSaplingTC.generateTree(BlockSaplingTC.java:87)
	at thaumcraft.common.blocks.world.plants.BlockSaplingTC.grow(BlockSaplingTC.java:81)
	at thaumcraft.common.blocks.world.plants.BlockSaplingTC.func_176474_b(BlockSaplingTC.java:172)
	at logictechcorp.netherex.handler.InputHandler.onBoneMealUse(InputHandler.java:177)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_722_InputHandler_onBoneMealUse_BonemealEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onApplyBonemeal(ForgeEventFactory.java:455)
	at net.minecraft.item.ItemDye.applyBonemeal(ItemDye.java:111)
	at net.minecraft.item.ItemDye.func_180614_a(ItemDye.java:55)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:187)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:477)
	at net.optifine.override.PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
`

**Comment by gegy1000** [comment]
@nathandstory: this crash seems to be unrelated to midnight, and rather a weird interaction between thaumcraft and openterraingenerator 
@GalacticRuler: do you see this crash if you only have midnight installed?

**Comment by nathandstory** [comment]
@gegy1000 Yes, mine is unrelated to midnight. I believe his is too. I also have reproduced it without OTG, and with a Pam's Harvestcraft sapling so that's why I am curious if NetherEx is involved since it is a similar error and it appears a NetherEX function is being called for both of us when we try to apply bonemeal. I'll do more testing and let you guys know if I figure anything out. If my crash is completely unrelated to his then I apologize, but I have a hunch it is related.

**Comment by gegy1000** [comment]
Ah, yes. It does look like an issue with NetherEx. It tries to generate the sapling on the client-side, which in the case of a lot of mods generally won't work.

**Comment by nathandstory** [comment]
Alright I'll open a help request with NetherEx in the morning if I cant resolve it in the next couple hours.

**Comment by nathandstory** [comment]
I opened up an issue with NetherEx here: https://github.com/LogicTechCorp/NetherEx/issues/187
if either of you are interested, I also deleted NetherEx and can confirm it is working now.

**Comment by Corail31** [comment]
fixed as shown on the netherEx issue.
