### ISSUE TITLE
Coremod transformer not finding a function, causing error

### ISSUE THREAD

**Issue by pez5150** [Cryptic-Mushroom/The-Midnight#375]
I have biome's o plenty installed. It looks like you're overwriting some basic vanilla biome stuff. I use the biomes o plenty world gen when creating new worlds. I think there may be a conflict between the two mods.

Mod list:
**03/31/2020  03:24 PM            22,121 AI-Improvements-1.15.2-0.3.0.jar
04/02/2020  10:01 AM            49,399 animalnet-v1.15.1+Forge+b1.jar
03/31/2020  03:23 PM            27,324 AppleSkin-mc1.15.2-forge-1.0.13.jar
04/02/2020  09:56 AM           472,031 Aquaculture-1.15.2-2.0.13.jar
03/31/2020  03:24 PM           205,671 astikorcarts-1.0.2-1.15.2.jar
03/31/2020  03:24 PM            58,933 AutoRegLib-1.5-40.jar
04/02/2020  09:57 AM            54,591 backpacked-1.4.1-1.15.2.jar
03/31/2020  04:27 PM         3,218,140 BiomesOPlenty-1.15.2-10.0.0.345-universal.jar
03/31/2020  03:23 PM             4,724 CHAS+v1.3+for+1.15.jar
04/07/2020  10:27 PM         1,891,111 Cyclic-1.15.2-0.3.0.jar
03/31/2020  04:38 PM           755,608 dimdungeons-1.051-forge-1.15.2.jar
03/31/2020  03:24 PM           795,820 DoggyTalents-1.15.2-1.15.2.3.jar
03/31/2020  03:23 PM           457,642 dwmh-1.15.2-4.0.0.jar
04/02/2020  10:30 AM            48,704 enchantedwolves-1.4.2.jar
03/31/2020  03:23 PM         1,371,365 extragolems-10.1.0.jar
03/31/2020  03:23 PM             8,321 FastLeafDecay-v20.jar
04/07/2020  10:27 PM         1,596,169 furniture-7.0.0-pre16-1.15.1.jar
04/02/2020  10:20 AM           393,460 goblintraders-1.2.0-1.15.2.jar
03/31/2020  03:23 PM           133,465 gravestone-1.17.3.jar
04/07/2020  10:51 PM            10,976 healingcf_1.15.2-1.7.jar
04/02/2020  10:39 AM             8,858 horsestandstill-1.15.2-1.0.0.jar
04/02/2020  10:40 AM            50,420 HunterMod-1.15.2-1.0.3.jar
04/07/2020  02:59 PM            80,218 invtweaks-1.15.2-1.0.3.jar
03/31/2020  03:23 PM           700,499 jei-1.15.2-6.0.0.2.jar
04/02/2020  10:22 AM           130,031 lava-monster-1.15.2-1.0.3.jar
04/07/2020  05:51 PM         6,627,951 Mekanism-1.15.2-9.9.18.410.jar
04/08/2020  08:48 AM           675,041 MekanismGenerators-1.15.2-9.9.18.410.jar
04/08/2020  08:49 AM           214,389 MekanismTools-1.15.2-9.9.18.410.jar
04/07/2020  10:51 PM        35,493,122 minecolonies-0.10.771-RELEASE-universal.jar
03/31/2020  03:23 PM           196,348 NaturesCompass-1.15.2-1.8.5.jar
03/31/2020  03:22 PM           189,698 OreExcavation-1.7.151.jar
04/07/2020  05:56 PM           525,840 Patchouli-1.15.2-1.2-30.jar
04/08/2020  08:43 AM         3,490,328 planttech2-0.01.07.jar
03/31/2020  03:24 PM         4,625,312 Quark-r2.1-227.jar
04/07/2020  10:27 PM         1,840,305 refinedstorage-1.8.1.jar
03/31/2020  03:22 PM            18,550 RingOfAttraction-1.15.2-1.1.23.jar
04/02/2020  10:34 AM            44,946 SBM-Magic-Mirror-1.15.2-1.0.1.jar
04/07/2020  11:00 PM            72,885 scarecrows-1.15.1-v1.0.8.jar
03/30/2020  06:35 PM         1,349,951 SilentGear-1.15.2-1.5.4+79.jar
03/31/2020  04:29 PM           207,267 SilentLib-1.15.2-4.6.0+48.jar
04/07/2020  10:30 PM         1,094,623 SilentMechanisms-1.15.2-0.7.0+50.jar
04/07/2020  01:56 PM           679,742 simplefarming-1.15.2-1.2.7.jar
04/02/2020  10:29 AM             8,886 skeletonhs_1.15.2-1.1.2.jar
04/08/2020  08:59 AM         4,734,071 structurize-0.10.282-RELEASE.jar
03/31/2020  03:24 PM         6,322,145 The-Endergetic-Expansion-1.15.2-v1.2.5.jar
04/07/2020  10:42 PM           200,858 ToolBelt-1.15.2-1.14.1.jar
03/31/2020  03:24 PM           253,907 XaerosWorldMap_1.5.6_Forge_1.15.2.jar
03/31/2020  03:23 PM           511,638 Xaeros_Minimap_20.5.2_Forge_1.15.2.jar
04/07/2020  10:29 PM           382,447 XL-Food-Mod-1.15.2-2.2.2.jar
04/02/2020  10:27 AM             8,832 zombiehs_1.15.2-2.1.2.jar**

Below is the error message I get when it loads. Eventually when I get to an area where your mod writes over a biome it stops loading chunks properly.

[08Apr2020 17:23:35.724] [Render thread/ERROR] [net.minecraftforge.coremod.transformer.CoreModBaseTransformer/COREMOD]: Error occurred applying transform of coremod midnight_core.js function LivingRendererTransformer
jdk.nashorn.internal.runtime.ECMAException: couldn't find method with name 'func_77043_a' in 'net/minecraft/client/renderer/entity/LivingRenderer'
	at jdk.nashorn.internal.runtime.ECMAException.create(ECMAException.java:113) ~[nashorn.jar:?]
	at jdk.nashorn.internal.scripts.Script$Recompilation$109$3805AA$\^eval\_.get_method(<eval>:105) ~[?:?]
	at jdk.nashorn.internal.scripts.Script$Recompilation$108$1921A$\^eval\_.patch_living_renderer(<eval>:56) ~[?:?]
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:638) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:229) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:387) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:110) ~[nashorn.jar:?]
	at net.minecraftforge.coremod.transformer.CoreModClassTransformer.runCoremod(CoreModClassTransformer.java:18) ~[coremods-2.0.0-milestone.1.jar:?]
	at net.minecraftforge.coremod.transformer.CoreModClassTransformer.runCoremod(CoreModClassTransformer.java:10) ~[coremods-2.0.0-milestone.1.jar:?]
	at net.minecraftforge.coremod.transformer.CoreModBaseTransformer.transform(CoreModBaseTransformer.java:38) [coremods-2.0.0-milestone.1.jar:?]
	at cpw.mods.modlauncher.TransformerHolder.transform(TransformerHolder.java:41) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.performVote(ClassTransformer.java:168) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:112) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:239) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:126) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96) [modlauncher-5.0.0-milestone.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.ClassLoader.defineClass1(Native Method) [?:1.8.0_51]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) [?:1.8.0_51]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642) [?:1.8.0_51]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:127) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96) [modlauncher-5.0.0-milestone.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:62) [eventbus-2.0.0-milestone.1-service.jar:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) [eventbus-2.0.0-milestone.1-service.jar:?]
	at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:20) [eventbus-2.0.0-milestone.1-service.jar:?]
	at net.minecraftforge.eventbus.service.ModLauncherService.processClass(ModLauncherService.java:20) [eventbus-2.0.0-milestone.1-service.jar:2.0.0-milestone.1+57+de55078]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:115) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:239) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:126) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96) [modlauncher-5.0.0-milestone.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at com.mcmoddev.golems.proxies.ProxyClient.<clinit>(ProxyClient.java:18) [?:10.1.0]
	at com.mcmoddev.golems.main.ExtraGolems.lambda$null$0(ExtraGolems.java:36) [?:10.1.0]
	at com.mcmoddev.golems.main.ExtraGolems$$Lambda$2267/1671191220.get(Unknown Source) [?:10.1.0]
	at net.minecraftforge.fml.DistExecutor.runForDist(DistExecutor.java:63) [?:?]
	at com.mcmoddev.golems.main.ExtraGolems.<clinit>(ExtraGolems.java:36) [?:10.1.0]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_51]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:71) [?:31.1]
	at sun.reflect.GeneratedConstructorAccessor51.newInstance(Unknown Source) [?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) [?:1.8.0_51]
	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) [forge-1.15.2-31.1.30-universal.jar:31.1]
	at net.minecraftforge.fml.ModLoader.buildModContainerFromTOML(ModLoader.java:234) [?:?]
	at net.minecraftforge.fml.ModLoader.lambda$buildMods$26(ModLoader.java:214) [?:?]
	at net.minecraftforge.fml.ModLoader$$Lambda$2155/1844498480.apply(Unknown Source) [?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) [?:1.8.0_51]
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1683) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) [?:1.8.0_51]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:1.8.0_51]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) [?:1.8.0_51]
	at net.minecraftforge.fml.ModLoader.buildMods(ModLoader.java:216) [?:?]
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$18(ModLoader.java:173) [?:?]
	at net.minecraftforge.fml.ModLoader$$Lambda$2152/214170716.apply(Unknown Source) [?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) [?:1.8.0_51]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) [?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) [?:1.8.0_51]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:1.8.0_51]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) [?:1.8.0_51]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:175) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:97) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2052/1172610365.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2053/120476166.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97) [?:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:393) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.30.jar:31.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$419/790432700.call(Unknown Source) [forge-1.15.2-31.1.30.jar:31.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?]

**Comment by Jonathing** [comment]
I've loaded the latest build of The Midnight with BOP 3.4.5 and Forge build 30 and I'm not getting the coremod transformer crash you're getting. It has nothing to do with biomes o plenty, but rather some other mod which is messing with the LivingEntity class transformer. If you can narrow down a cause, I'll try testing it again. If not, I'll close the issue three days from now.

**Comment by RedGalaxySW** [comment]
This error appears in my log files too, even in the IDE - Forge just doesn't crash:
https://github.com/Cryptic-Mushroom/The-Midnight/blob/1.15.2/src/main/resources/midnight_core.js#L63... This has nothing to do with BOP and a chunk loading hang however...

Though I might have reproduced it as I've seen the Midnight just running into some weird condition where chunk loading completely stops, even without biomes o plenty...

**Comment by RedGalaxySW** [comment]
The error message is fixed...
#377 references the issue with chunk loading, they are the same bug...

**Comment by Jonathing** [comment]
@RedGalaxySW Gotcha. Didn't realize. Thanks!
