### ISSUE TITLE
plugin.yml missing from jars

### ISSUE THREAD

**Issue by DeFoon** [Cryptic-Mushroom/The-Midnight#393]
I'm downloading the jars from curse forge and i'm checking them before i upload to the server, but i'm not seeing any plugin.yml files so it fails to start. 

I'm pretty sure im missing something or am blind and cannot see what config step i'm missing. Here is the startup error i see when attempting to use the plugin with 1.15.2

[13:38:22 ERROR]: Could not load 'plugins\themidnight-0.5.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-2040c4c-a1a705e]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:144) [spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-2040c4c-a1a705e]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:353) [spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-2040c4c-a1a705e]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:210) [spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-2040c4c-a1a705e]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-2040c4c-a1a705e]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml

**Comment by Jonathing** [comment]
The Midnight is a Forge mod, not a Spigot plugin.
