### ISSUE TITLE
Mobs crashing game

### ISSUE THREAD

**Issue by GrimmBread** [Cryptic-Mushroom/The-Midnight#402]
DO NOT REPORT ANY ISSUES ON THE 1.12.2 VERSIONS OF THE MIDNIGHT: THOSE VERSIONS ARE NO LONGER SUPPORTED AND ANY RELATING ISSUE WILL BE CLOSED AND IGNORED!!!

Explain the bug:
- What isn't working?
**Sorry I don't know the names of the mobs. When the deer like creatures, and the small scorpion looking ones I found in a cave come towards me, the game will freeze and crash. This hasn't happened with any other mobs I've encountered yet.**
- How to reproduce the problem?
**Enter a range that they will come towards the player**
- Does the game crash? How?
**Yes, it freezes, saves the world, and then crashes.**
Be clear and concise.

If you have some screenshots, please include them. They are very helpful to understand the issue.

If the game crashes, please paste the crash report here (code block!!) or in a gist/pastebin. When the game crashes, the launcher will probably show you a link to open the crash report (old launchers just shows the crash report itself).

---- Minecraft Crash Report ----
// My bad.

Time: 07/05/20 10:23 PM
Description: Unexpected error

java.lang.IllegalStateException: Cannot get ExtendedCreature from EntityCreature StingerEntity['Stinger'/5041, l='MpServer', x=13851.10, y=45.00, z=3404.55]
	at de.teamlapen.vampirism.entity.ExtendedCreature.lambda$getUnsafe$0(ExtendedCreature.java:50) ~[?:1.6.0-beta.1] {re:classloading}
	at de.teamlapen.vampirism.entity.ExtendedCreature$$Lambda$6178/1201351431.get(Unknown Source) ~[?:?] {}
	at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:261) ~[?:?] {re:classloading}
	at de.teamlapen.vampirism.entity.ExtendedCreature.getUnsafe(ExtendedCreature.java:50) ~[?:1.6.0-beta.1] {re:classloading}
	at de.teamlapen.vampirism.client.gui.VampirismHUDOverlay.onRenderCrosshair(VampirismHUDOverlay.java:146) ~[?:1.6.0-beta.1] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_150_VampirismHUDOverlay_onRenderCrosshair_Pre.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.client.gui.ForgeIngameGui.pre(ForgeIngameGui.java:826) ~[?:?] {re:classloading}
	at net.minecraftforge.client.gui.ForgeIngameGui.func_194798_c(ForgeIngameGui.java:227) ~[?:?] {re:classloading}
	at net.minecraftforge.client.gui.ForgeIngameGui.func_175180_a(ForgeIngameGui.java:156) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:744) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:925) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.0.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$412/2141932519.call(Unknown Source) [forge-1.15.2-31.1.0.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at de.teamlapen.vampirism.entity.ExtendedCreature.lambda$getUnsafe$0(ExtendedCreature.java:50)
	at de.teamlapen.vampirism.entity.ExtendedCreature$$Lambda$6178/1201351431.get(Unknown Source)
	at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:261)
	at de.teamlapen.vampirism.entity.ExtendedCreature.getUnsafe(ExtendedCreature.java:50)
	at de.teamlapen.vampirism.client.gui.VampirismHUDOverlay.onRenderCrosshair(VampirismHUDOverlay.java:146)
	at net.minecraftforge.eventbus.ASMEventHandler_150_VampirismHUDOverlay_onRenderCrosshair_Pre.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.client.gui.ForgeIngameGui.pre(ForgeIngameGui.java:826)
	at net.minecraftforge.client.gui.ForgeIngameGui.func_194798_c(ForgeIngameGui.java:227)
	at net.minecraftforge.client.gui.ForgeIngameGui.func_175180_a(ForgeIngameGui.java:156)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['GrimmFritter'/1228, l='MpServer', x=13853.40, y=45.00, z=3404.75]]
	Chunk stats: Client Chunk Cache: 1369, 1024
	Level dimension: DimensionType{midnight:midnight}
	Level name: MpServer
	Level seed: 6649818632451353089
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (160,63,-83), Chunk: (at 0,3,13 in 10,-6; contains blocks 160,0,-96 to 175,255,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 484619 game time, 741142 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:611)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1764)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:573)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$412/2141932519.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2981061256 bytes (2842 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.0-milestone.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre16.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.0
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.0-client.jar Minecraft {minecraft@1.15.2 DONE}
		backpacked-1.4.1-1.15.2.jar Backpacked {backpacked@1.4.1 DONE}
		themidnight-0.5.7-3.jar The Midnight {midnight@0.5.7-3 DONE}
		AmbientSounds_v3.0.17_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		forge-1.15.2-31.1.0-universal.jar Forge {forge@31.1.0 DONE}
		BiomesOPlenty-1.15.2-10.0.0.345-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.342 DONE}
		Blur-1.1.0-1.jar Blur {blur@1.1.0-1 DONE}
		Xaeros_Minimap_20.9.0_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.9.0 DONE}
		Vampirism-1.15.2-1.6.0-beta.1.jar Vampirism {vampirism@1.6.0-alpha+20200505-0114 DONE, teamlapenlib@1.6.0-alpha+20200505-0114 DONE}
		sit-1.15.1-v1.3.jar Sit {sit@v1.3 DONE}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 DONE}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 DONE}
	Launched Version: 1.15.2-forge-31.1.0
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 442.74, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre16
	OptiFine Build: 20200506-004910
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.27 High.zip
	OpenGlVersion: 4.6.0 NVIDIA 442.74
	OpenGlRenderer: GeForce GTX 1080 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

If you have found some remarkable log messages, please include only those messages (code block!!) and paste the complete log file in a gist/pastebin.

#### Environment
- Midnight: 0.5.7-3
- Forge: 31.1.0
- Did you use other remarkable modpacks, mods, resource packs or data packs, please list them here too.

**Most of my mods are light/cosmetic, the two heavier ones I'm using are Vampirism and Biomes O' Plenty.**

**Comment by GrimmBread** [comment]
To clarify a bit: When I approach Nightstags and Stingers, the game will crash. I'm not sure if they're supposed to, but the Nightstags will start walking as if they're aggro (I did not attack). The Stingers will do they same of course, and the game will crash around a second after they start approaching.

**Comment by RedGalaxySW** [comment]
The crash is generally caused by Vampirism: they try to do something on our stuff and assume we have given support for it but we haven't (they may not assume this so they are the cause)
Please report this issue on their bug tracker (add a link here)

**Comment by maxanier** [comment]
They didn't bother creating an issue at our repository, but I found this by accident anyway.

Yes, this is something that should be solved (crash safe) at our end. Will do so.
However, I did not understand what is actually causing this issue yet.
Vampirism attaches a capability to all `CreatureEntity` and later on reads this. This not something a mod has to "give support" for, but something that is intended by Forge.
Usually the capability remains valid as long as the entity isn't removed, therefore Vampirism assumes it is safe to access. (However, this is our mistake, as capabilities are designed to be "invalidate-able")
Still, I don't see anything in `StingerEntity` nor `GrowableEntity` that would mess with capabilities.
Does some other part of the mod, teleport entities or invalidate caps?

**Comment by Jonathing** [comment]
@maxanier thanks for your input! The mobs in the midnight should spawn as creatures in their own so I don't get what the issue is either.

**Comment by RedGalaxySW** [comment]
Both mobs seem to use `AnimationCapability`... Hunters also have that: does it happen with Hunters too?

I doubt if `AnimationCapability` is the cause though, since it's initialized directly within the entity itself and not as a Forge capability so nothing would clash...

**Comment by maxanier** [comment]
Oh, apparently I didn't check the code thoroughly enough

At least the `StingerEntity` overrides `getCapability`
https://github.com/Cryptic-Mushroom/The-Midnight/blob/ecce87a7da523ae592bcb3fe7d6588d0c877a772/src/main/java/com/mushroom/midnight/common/entity/creature/StingerEntity.java#L203
Should probably return `super.getCapability` instead of empty for anything but the animationcapability

**Comment by RedGalaxySW** [comment]
Oh that's definitely it, and still our fault :|
We'll fix it with the rewrite for 1.16. @maxanier Thanks for helping!
