### ISSUE TITLE
Waterfall incompatibility when connecting to vanilla lobby server.

### ISSUE THREAD

**Issue by MikeHollisJr** [Cryptic-Mushroom/The-Midnight#428]
The Midnight is incompatible with Waterfall, once I removed the mod from the client I was able to connect to a vanilla lobby, could you consider allowing for this exception?

This is tested with Valhelsia 2 v2.2.3  on MC 1.15.2 with waterfall 360 and spongeforge 1.12.2 using ViaVersion for allowing mismatched versions to connect.

```
[m[32m[17:31:32] [Realms Notification Availability checker #1/INFO] [mojang/RealmsClient]: Could not authorize you against Realms server: Invalid session id
[m[RandomPatches ServerLoginNetHandler Transformer]: Patching method: func_73660_a (func_73660_a)
[1;31m[17:32:03] [Netty Client IO #0/ERROR] [ne.mi.fm.ne.NetworkRegistry/NETREGISTRY]: Channels [mininggadgets:main_network_channel,embellishcraft:embellishcraft_channel,cfm:network,refinedpipes:main_channel,silentlib:network,lollipop:main,computercraft:network,darkutils:main,essentials:channel,autoreglib:main,endergetic:net,upgrade_aquatic:net,immersiveengineering:main,cosmeticarmorreworked:main,mekanism:mekanism,caelus:main,toolbelt:general,fluxnetworks:main,botania:chan,lightestlamp:main,sereneseasons:main_channel,powah:main,kiwi:main,comforts:main,doubleslabs:main,cookingforblockheads:network,mekanismgenerators:mekanismgenerators,storagedrawers:main_channel,midnight:net,abnormals_core:net,psi:main,curios:main,polymorph:main,structurize:net-channel,minecolonies:net-channel,quark:main,silentgear:network,miscadditions:main_channel,storagenetwork:main_channel,patchouli:main,uteamcore:network,silents_mechanisms:network,doggytalents:channel,elevatorid:main_channel,waystones:network,refinedstorage:main_channel] rejected vanilla connections
[m[1;31m[17:32:03] [Netty Client IO #0/ERROR] [ne.mi.fm.ne.NetworkRegistry/NETREGISTRY]: Channels [mininggadgets:main_network_channel,embellishcraft:embellishcraft_channel,cfm:network,refinedpipes:main_channel,silentlib:network,lollipop:main,computercraft:network,darkutils:main,essentials:channel,autoreglib:main,endergetic:net,upgrade_aquatic:net,immersiveengineering:main,cosmeticarmorreworked:main,mekanism:mekanism,caelus:main,toolbelt:general,fluxnetworks:main,botania:chan,lightestlamp:main,sereneseasons:main_channel,powah:main,kiwi:main,comforts:main,doubleslabs:main,cookingforblockheads:network,mekanismgenerators:mekanismgenerators,storagedrawers:main_channel,midnight:net,abnormals_core:net,psi:main,curios:main,polymorph:main,structurize:net-channel,minecolonies:net-channel,quark:main,silentgear:network,miscadditions:main_channel,storagenetwork:main_channel,patchouli:main,uteamcore:network,silents_mechanisms:network,doggytalents:channel,elevatorid:main_channel,waystones:network,refinedstorage:main_channel] rejected vanilla connections
[m[32m[17:32:09] [Render thread/INFO] [mojang/YggdrasilUserAuthentication]: Logging in with username & password
[m[32m[17:32:16] [Render thread/INFO] [minecraft/ConnectingScreen]: Connecting to game.mcbadwolf.com, 25565
[m[RandomPatches NettyCompressionDecoder Transformer]: Transforming class: net/minecraft/network/NettyCompressionDecoder
[RandomPatches NettyCompressionDecoder Transformer]: Patching method: decode (decode)
[32m[17:32:16] [Netty Client IO #1/INFO] [ne.mi.fm.ne.NetworkHooks/]: Connected to a vanilla server. Catching up missing behaviour.
[m[1;31m[17:32:16] [Netty Client IO #1/ERROR] [ne.mi.fm.ja.FMLModContainer/]: Exception caught during firing event: null
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: class com.mushroom.midnight.client.ClientProxy onConfigLoad(Lnet/minecraftforge/fml/config/ModConfig$Loading;)V
java.lang.NullPointerException
	at net.minecraftforge.fml.LogicalSidedProvider.lambda$static$3(LogicalSidedProvider.java:33)
	at net.minecraftforge.fml.LogicalSidedProvider.get(LogicalSidedProvider.java:60)
	at com.mushroom.midnight.client.ClientProxy.onConfigLoad(ClientProxy.java:91)
	at net.minecraftforge.eventbus.ASMEventHandler_608_ClientProxy_onConfigLoad_Loading.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:66)
	at net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$5(ModContainer.java:147)
	at java.util.Optional.ifPresent(Unknown Source)
	at net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:147)
	at net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:89)
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadDefaultServerConfigs$6(ConfigTracker.java:133)
	at java.lang.Iterable.forEach(Unknown Source)
	at java.util.Collections$SynchronizedCollection.forEach(Unknown Source)
	at net.minecraftforge.fml.config.ConfigTracker.loadDefaultServerConfigs(ConfigTracker.java:129)
	at net.minecraftforge.fml.network.NetworkHooks.handleClientLoginSuccess(NetworkHooks.java:127)
	at net.minecraft.client.network.login.ClientLoginNetHandler.func_147390_a(ClientLoginNetHandler.java:101)
	at net.minecraft.network.login.server.SLoginSuccessPacket.func_148833_a(SLoginSuccessPacket.java:36)
	at net.minecraft.network.login.server.SLoginSuccessPacket.func_148833_a(SLoginSuccessPacket.java:12)
	at net.minecraft.network.NetworkManager.func_197664_a(NetworkManager.java:149)
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:138)
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:49)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by Jonathing** [comment]
Yeah, that's on us, sorry. The game's crashing because the mod's trying to load the config in a way that does not exist in 1.12.2. Although, it shouldn't be an issue because it has almost nothing to do if you connect to a server. There's not much we can really do about this since we've taken our focus off of 1.15.2 and onto 1.16.x, but feel free to update this issue if you come up with any solutions on your end.
