### ISSUE TITLE
[1.15.2] Sever crashed when loading midnight dimension

### ISSUE THREAD

**Issue by sandtechnology** [Cryptic-Mushroom/The-Midnight#445]
# The Bug
Sever crashed when loading midnight dimension.

# Steps to reproduce
Unknown

# Important Notes
It was randomly happening when loading midnight dimension, and I'm using [Arclight](https://github.com/IzzelAliz/Arclight) server software.
Crash-report: https://paste.ubuntu.com/p/Pgp6D9dbfx/
Logs: https://paste.ubuntu.com/p/sxhkVsX5PB/

## Environment

- Minecraft: 1.15.2
- Midnight: 0.5.10
- Forge: 31.2.45
- Server: Arclight (https://github.com/IzzelAliz/Arclight)

**Comment by Jonathing** [comment]
We do not support Java 11+ with our mods. Minecraft targets Java 8 so we target Java 8 as well. Try again using Java 8 instead and if the issue persists, feel free to re-open the issue with updated crash reports and logs. Also, I have no idea how Arclight works as I've never heard of it, so no promises it'll work with that since the codebase for the 1.15.2 version of the Midnight is a huge mess.

**Comment by Jipok** [comment]
> Minecraft targets Java 8 so we target Java 8 as well.

Minecraft works great on openjdk11 and openjdk14. Moreover, on weak laptops, it has a FPS 1.5-2 times more than with 8 Java.
Could you get rid of the legacy and make the mod run on normal java?
I have a great modpack with about 100 mods. Only one midnight causes problems. My friends have weak laptops and on the 8th Java they give out 15-30 fps. And without midnight on the 14th Java, about 50 fps.

**Comment by ShadewEnder** [comment]
We might consider this in the rewrite, but right now I cannot promise anything about this. If we would get some testers who test on Java 9+ we might consider this. At least we won't support this in 0.5.x anymore...

**Comment by ShadewEnder** [comment]
This issue seems to be some concurrency issue in level generation, something we are completely changing (not only internally but also visually). It is caused by a templated feature (a thing, e.g. a fungus tree in this case, that is generated from an NBT structure template). What the exact goal here will be isn't completely worked out yet. But as I said we're changing levelgen drastically so we'll re-evaluate things here and we'll hopefully fix this.

**Comment by Jipok** [comment]
> rewrite

Are you rewriting the mod? Will there be any major changes? Where can you read about it? Forge or/and Fabric? 15.2?

> If we would get some testers who test on Java 9+ we might consider this. 

If it will be in the next week or two, then I can test both on Windows and Linux on the 11th and 14th Java.

> This issue seems ....

In fact, my message has nothing to do with this issue. I just found the first mention of the fact that you do not support the fresh Java. I think someone has already created a report. On the 14th Java, the client does not even start.
<details> 
  <summary>log</summary>

```
[16:38:44] [modloading-worker-1/INFO] [co.mu.mi.Midnight/]: Initializing The Midnight
[16:38:44] [modloading-worker-2/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 31.2.45, for MC 1.15.2 with MCP 20200515.085601
[16:38:44] [modloading-worker-2/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v31.2.45 Initialized
[16:38:44] [modloading-worker-1/INFO] [co.mu.mi.Midnight/]:  - Version: 0.5.11
[16:38:44] [modloading-worker-1/INFO] [co.mu.mi.Midnight/]:  - Dist: CLIENT
[16:38:45] [modloading-worker-1/WARN] [minecraft/EntityType]: No data fixer registered for entity midnight:rifter
[16:38:45] [modloading-worker-1/WARN] [minecraft/EntityType]: No data fixer registered for entity midnight:hunter
[16:38:45] [modloading-worker-1/WARN] [minecraft/EntityType]: No data fixer registered for entity midnight:bladeshroom_cap
[16:38:45] [modloading-worker-1/WARN] [minecraft/EntityType]: No data fixer registered for entity midnight:nova
[16:38:45] [modloading-worker-1/WARN] [minecraft/EntityType]: No data fixer registered for entity midnight:nova_spike
[16:38:45] [modloading-worker-1/WARN] [minecraft/EntityType]: No data fixer registered for entity midnight:crystal_bug
[16:38:45] [modloading-worker-1/WARN] [minecraft/EntityType]: No data fixer registered for entity midnight:penumbrian
[16:38:45] [modloading-worker-1/WARN] [minecraft/EntityType]: No data fixer registered for entity midnight:tree_hopper
[16:38:45] [modloading-worker-1/WARN] [minecraft/EntityType]: No data fixer registered for entity midnight:stinger
[16:38:45] [modloading-worker-1/WARN] [minecraft/EntityType]: No data fixer registered for entity midnight:nightstag
[16:38:45] [modloading-worker-1/WARN] [minecraft/EntityType]: No data fixer registered for entity midnight:deceitful_snapper
[16:38:45] [modloading-worker-1/WARN] [minecraft/EntityType]: No data fixer registered for entity midnight:bulb_angler
[16:38:45] [modloading-worker-1/WARN] [minecraft/EntityType]: No data fixer registered for entity midnight:skulk
[16:38:45] [modloading-worker-1/WARN] [minecraft/EntityType]: No data fixer registered for entity midnight:shade_squirrel
[16:38:45] [modloading-worker-1/WARN] [minecraft/EntityType]: No data fixer registered for entity midnight:thrown_geode
[16:38:45] [modloading-worker-1/WARN] [minecraft/EntityType]: No data fixer registered for entity midnight:spore_bomb
[16:38:45] [modloading-worker-1/WARN] [minecraft/EntityType]: No data fixer registered for entity midnight:cloud
[16:38:46] [Render thread/WARN] [co.mu.mi.Midnight/]: Failed to reflect strippable logs field
java.lang.NoSuchFieldException: modifiers
	at java.lang.Class.getDeclaredField(Class.java:2489) ~[?:?] {}
	at com.mushroom.midnight.common.item.tool.MidnightAxeItem.<clinit>(MidnightAxeItem.java:20) ~[?:0.5.11] {re:classloading}
	at com.mushroom.midnight.common.registry.MidnightItems.lambda$registerItems$16(MidnightItems.java:148) ~[?:0.5.11] {re:mixin,pl:object_holder_definalize:A,re:classloading,pl:object_holder_definalize:A}
	at com.mushroom.midnight.common.registry.RegUtil$Items.add(RegUtil.java:60) ~[?:0.5.11] {re:classloading}
	at com.mushroom.midnight.common.registry.MidnightItems.registerItems(MidnightItems.java:148) ~[?:0.5.11] {re:mixin,pl:object_holder_definalize:A,re:classloading,pl:object_holder_definalize:A}
	at net.minecraftforge.eventbus.ASMEventHandler_14_MidnightItems_registerItems_Register.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106) ~[?:31.2] {re:classloading}
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:?] {}
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:126) ~[?:?] {re:classloading}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1624) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?] {}
	at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:126) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:214) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$25(ModLoader.java:206) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:995) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:206) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:97) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:392) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) ~[minecraft-1.15.2-client.jar:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.15.2-31.2.45-launcher.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.2.jar:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}
[16:38:49] [Render thread/INFO] [mojang/NarratorLinux]: Narrator library successfully loaded
[16:38:49] [Render thread/INFO] [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: Default, Mod Resources
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.mushroom.midnight.common.util.EnumUtil to field java.lang.Class.enumConstants
WARNING: Please consider reporting this to the maintainers of com.mushroom.midnight.common.util.EnumUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[16:38:50] [modloading-worker-1/ERROR] [ne.mi.fm.ja.FMLModContainer/]: Exception caught during firing event: null
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2250/0x0000000801425c40@2b8d2064
		2: net.minecraftforge.eventbus.EventBus$$Lambda$2250/0x0000000801425c40@23857baa
java.lang.ExceptionInInitializerError
	at com.mushroom.midnight.client.ClientProxy.setup(ClientProxy.java:53)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106)
	at java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
	at java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112)
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:135)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1624)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)
	at net.minecraftforge.fml.ModList.lambda$dispatchParallelEvent$11(ModList.java:135)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1409)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.RuntimeException: Can't add enum
	at com.mushroom.midnight.common.util.EnumUtil.addEnum(EnumUtil.java:139)
	at com.mushroom.midnight.common.recipe.MidnightRecipeBookCategories.<clinit>(MidnightRecipeBookCategories.java:11)
	... 29 more
Caused by: java.lang.NoSuchFieldException: modifiers
	at java.base/java.lang.Class.getDeclaredField(Class.java:2489)
	at com.mushroom.midnight.common.util.EnumUtil.buildEnum(EnumUtil.java:43)
	at com.mushroom.midnight.common.util.EnumUtil.addEnum(EnumUtil.java:137)
	... 30 more

[16:38:50] [modloading-worker-1/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Caught exception during event FMLCommonSetupEvent dispatch for modid midnight
java.lang.ExceptionInInitializerError: null
	at com.mushroom.midnight.client.ClientProxy.setup(ClientProxy.java:53) ~[?:0.5.11] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106) ~[?:31.2] {re:classloading}
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:?] {}
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:135) ~[?:?] {re:classloading}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1624) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[?:?] {}
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661) ~[?:?] {}
	at net.minecraftforge.fml.ModList.lambda$dispatchParallelEvent$11(ModList.java:135) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1409) [?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) [?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) [?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) [?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) [?:?] {}
Caused by: java.lang.RuntimeException: Can't add enum
	at com.mushroom.midnight.common.util.EnumUtil.addEnum(EnumUtil.java:139) ~[?:0.5.11] {re:classloading}
	at com.mushroom.midnight.common.recipe.MidnightRecipeBookCategories.<clinit>(MidnightRecipeBookCategories.java:11) ~[?:0.5.11] {re:classloading}
	... 29 more
Caused by: java.lang.NoSuchFieldException: modifiers
	at java.lang.Class.getDeclaredField(Class.java:2489) ~[?:?] {}
	at com.mushroom.midnight.common.util.EnumUtil.buildEnum(EnumUtil.java:43) ~[?:0.5.11] {re:classloading}
	at com.mushroom.midnight.common.util.EnumUtil.addEnum(EnumUtil.java:137) ~[?:0.5.11] {re:classloading}
	at com.mushroom.midnight.common.recipe.MidnightRecipeBookCategories.<clinit>(MidnightRecipeBookCategories.java:11) ~[?:0.5.11] {re:classloading}
	... 29 more
[16:38:50] [Server-Worker-2/FATAL] [ne.mi.fm.ModLoader/LOADING]: Failed to complete lifecycle event SETUP, 1 errors found
[16:38:50] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: Global Forge version check system disabled, no further processing.
[16:38:50] [Server-Worker-2/FATAL] [ne.mi.ev.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.startModLoading(ClientModLoader.java:123) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$3(ClientModLoader.java:105) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) [?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) [?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) [?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) [?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) [?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) [?:?] {}
[16:38:52] [Server-Worker-5/ERROR] [ne.mi.fm.ModLoader/LOADING]: Skipping lifecycle event ENQUEUE_IMC, 1 errors found.
[16:38:52] [Server-Worker-5/FATAL] [ne.mi.fm.ModLoader/LOADING]: Failed to complete lifecycle event ENQUEUE_IMC, 1 errors found
[16:38:52] [Server-Worker-5/FATAL] [ne.mi.ev.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.finishModLoading(ClientModLoader.java:137) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$4(ClientModLoader.java:107) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783) [?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479) [?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) [?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) [?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) [?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) [?:?] {}

```
</details>

**Comment by sandtechnology** [comment]
> 11th
11th Java can start with this jvm args as I mentioned in this issue: #412 
`--add-opens java.base/jdk.internal.reflect=ALL-UNNAMED`

14th Java look like the reflection has completely broken, so the code need to adapt to it unfortunately.

Also it should be a separate issue.

**Comment by Jipok** [comment]
> --add-opens java.base/jdk.internal.reflect=ALL-UNNAMED

Interesting. Although the names are confusing. This is probably breaking something in mod?

**Comment by sandtechnology** [comment]
> 
> 
> > --add-opens java.base/jdk.internal.reflect=ALL-UNNAMED
> 
> Interesting. Although the names are confusing. This is probably breaking something in mod?

It just allow all unnamed modules access to jdk.internal.reflect package which in java.base module, nothing to do with any mod.

**Comment by ShadewEnder** [comment]
> Are you rewriting the mod? Will there be any major changes? Where can you read about it? Forge or/and Fabric? 15.2?

See this page (which is probably not completely up to date): https://the-midnight.readthedocs.io/en/latest/rewrite/  
Or check discord #faq: https://discord.gg/h7u4Tc7

---

> If it will be in the next week or two, then I can test both on Windows and Linux on the 11th and 14th Java.

If you wanna help testing you'd probably get to @Jonathing. Meanwhile I'm working on doing some tests automatically but this will probably not include testing different Java versions, and we'll still need some testers.

---

> In fact, my message has nothing to do with this issue. I just found the first mention of the fact that you do not support the fresh Java. I think someone has already created a report. On the 14th Java, the client does not even start.

Yes, but the original issue was just a concurrency issue and the reflection issues did not appear at all.

---

When it comes to reflection, I'll take some more care of not using reflection when it comes to supporting new Java versions. Reflection seems to be the only thing breaking things in Java 9+, and meanwhile Forge gave us Access Transformers which use ASM to modify the `public`, `private`, `final`, `protected` stuff of classes, fields, methods, constructors, etc. in addition to all the API patches Forge already provides, so we get there without the need of reflection :).

**Comment by ShadewEnder** [comment]
Please continue the Java 9+ discussion in #446 now
