### ISSUE TITLE
[1.12.2] FMLIndexedMessageCodec exception caught

### ISSUE THREAD

**Issue by Kennar** [Cryptic-Mushroom/The-Midnight#450]
Hello.
When walking with friends on the server at night, when the portal is created, errors appear in the logs, or you can ask for a bug fix:
`[21:26:50] [Server thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught
io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250) [SimpleNetworkWrapper.class:?]
	at com.mushroom.midnight.common.entity.BridgeTracker.sendToTracking(BridgeTracker.java:51) [BridgeTracker.class:?]
	at com.mushroom.midnight.common.entity.BridgeTracker.update(BridgeTracker.java:27) [BridgeTracker.class:?]
	at com.mushroom.midnight.common.entity.RiftBridge.tickState(RiftBridge.java:66) [RiftBridge.class:?]
	at com.mushroom.midnight.common.world.BridgeManagerServer.update(BridgeManagerServer.java:46) [BridgeManagerServer.class:?]
	at com.mushroom.midnight.common.CommonEventHandler.onWorldTick(CommonEventHandler.java:129) [CommonEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_340_CommonEventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:752) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1408) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.buffer.UnpooledHeapByteBuf.capacity(UnpooledHeapByteBuf.java:114) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.buffer.UnpooledHeapByteBuf.setBytes(UnpooledHeapByteBuf.java:254) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1069) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1060) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1050) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraft.network.PacketBuffer.writeBytes(PacketBuffer.java:1094) ~[gy.class:?]
	at com.mushroom.midnight.common.network.MessageBridgeState.toBytes(MessageBridgeState.java:35) ~[MessageBridgeState.class:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:30) ~[SimpleIndexedCodec.class:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:26) ~[SimpleIndexedCodec.class:?]
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:81) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[minecraft_server.1.12.2.jar:?]
	... 23 more`

**Comment by ShadewEnder** [comment]
Ok so first of all, this is an 1.12.2 bug which got resolved in a later 1.14/1.15 version. We no longer support 1.12.
Second of all, when it is only log messages and no breakage of functionality there is no need for reporting it, log messages never are bugs :)

**Comment by Kennar** [comment]
And in which version exactly has this been fixed?

**Comment by ShadewEnder** [comment]
In the first 1.14 version this is fixed. All 1.12 versions are quite unstable, and as far as I get the log message it's a Forge bug (and Forge was rewritten a lot in 1.13, including the part causing this issue).
